return { -- Useful plugin to show you pending keybinds.
	"folke/which-key.nvim",
	event = "VimEnter", -- Sets the loading event to 'VimEnter'
	config = function() -- This is the function that runs, AFTER loading
		-- Document existing key chains
		require("which-key").add({
			{ "<leader>f", icon = { icon = "", color = "orange" } },
			{ "<leader>fn", icon = { icon = "", color = "orange" } },
			{ "<leader>ff", icon = { icon = "󰱽", color = "orange" } },
			{ "<leader>fG", icon = { icon = "󰊢", color = "orange" } },
			{ "<leader>fh", icon = { icon = "󱤈", color = "orange" } },
			{ "<leader>fs", icon = { icon = "󰨽", color = "orange" } },
			{ "<leader>fc", icon = { icon = "󰺯", color = "orange" } },
			{ "<leader>fd", icon = { icon = "󰶚", color = "orange" } },
			{ "<leader>f/", icon = { icon = "󱩾", color = "orange" } },
			{ "<leader>fb", icon = { icon = "󰏢", color = "orange" } },
			{ "<leader>ft", icon = { icon = "", color = "orange" } },
			{ "<leader>fr", icon = { icon = "", color = "orange" } },
			{ "<leader>b", icon = { icon = "󰏢", color = "green" } },
			{ "<leader>bc", icon = { icon = "", color = "green" } },
			{ "<leader>br", icon = { icon = "", color = "green" } },
			{ "<leader>bca", icon = { icon = "󰪦", color = "green" } },
			{ "<leader>bcl", icon = { icon = "󰶺", color = "green" } },
			{ "<leader>bcr", icon = { icon = "󰶻", color = "green" } },
			{ "<leader>bcc", icon = { icon = "󰶹", color = "green" } },
			{ "<leader>g", icon = { icon = "󰊢", color = "red" } },
			{ "<leader>gb", icon = { icon = "", color = "red" } },
			{ "<leader>gd", icon = { icon = "󰕚", color = "red" } },
			{ "<leader>gD", icon = { icon = "", color = "red" } },
			{ "<leader>gp", icon = { icon = "", color = "red" } },
			{ "<leader>gr", icon = { icon = "󰝳", color = "red" } },
			{ "<leader>gR", icon = { icon = "󰝳", color = "red" } },
			{ "<leader>gu", icon = { icon = "", color = "red" } },
			{ "<leader>gs", icon = { icon = "", color = "red" } },
			{ "<leader>gS", icon = { icon = "", color = "red" } },
			{ "<leader>x", icon = { icon = "󰻍", color = "red" } },
			{ "<leader>l", icon = { icon = "󰒲", color = "blue" } },
			{ "<leader>s", icon = "" },
			{ "<leader>e", icon = { icon = "", color = "yellow" } },
			{ "<leader>ec", icon = { icon = "󰡌", color = "yellow" } },
			{ "<leader>ee", icon = { icon = "󰨚", color = "yellow" } },
			{ "<leader>er", icon = { icon = "", color = "yellow" } },
			{ "<leader>ef", icon = { icon = "󰙅", color = "yellow" } },
			{ "<leader>m", icon = { icon = "󰽛", color = "green" } },
			{ "<leader>mp", icon = { icon = "", color = "green" } },
			{ "<leader>d", icon = { icon = "", color = "red" } },
			{ "<leader>D", icon = { icon = "", color = "red" } },
			{ "<leader>q", icon = { icon = "󰩈", color = "orange" } },
			{ "<leader>o", icon = { icon = "󰨚", color = "orange" } },
			{ "<leader>c", icon = { icon = "", color = "red" } },
		})
		require("which-key").setup()
	end,
}
