format = """
$username\
$directory\
$git_branch\
$git_status\
$fill\
$c\
$custom\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
$conda\
$python\
$time\n  \
[󱞪](fg:magenta) \
"""

palette = "tokyonight"

[palettes.tokyonight]
overlay = '#292e42' # bg_highlight
blue = '#7aa2f7'
cyan = '#7dcfff'
green = '#9ece6a'
magenta = '#bb9af7'
orange = '#ff9e64'
purple = '#9d7cd8'
red = '#f7768e'
teal = '#1abc9c'
yellow = '#e0af68'
fg = '#c0caf5'

[directory]
format = "[](fg:overlay)[ $path ]($style)[](fg:overlay) "
style = "bg:overlay fg:blue"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
Documents = "󰈙"
Downloads = " "
Music = " "
Pictures = " "

[fill]
style = "fg:overlay"
symbol = " "

[git_branch]
format = "[](fg:overlay)[ $symbol $branch ]($style)[](fg:overlay) "
style = "bg:overlay fg:cyan"
symbol = ""

[git_status]
disabled = false
style = "bg:overlay fg:red"
format = '[](fg:overlay)([$all_status$ahead_behind]($style))[](fg:overlay) '
up_to_date = '[ ✓ ](bg:overlay fg:green)'
untracked = '[?\($count\)](bg:overlay fg:yellow)'
stashed = '[\$](bg:overlay fg:cyan)'
modified = '[!\($count\)](bg:overlay fg:orange)'
renamed = '[»\($count\)](bg:overlay fg:blue)'
deleted = '[✘\($count\)](style)'
staged = '[++\($count\)](bg:overlay fg:yellow)'
ahead = '[⇡\(${count}\)](bg:overlay fg:cyan)'
diverged = '⇕[\[](bg:overlay fg:blue)[⇡\(${ahead_count}\)](bg:overlay fg:cyan)[⇣\(${behind_count}\)](bg:overlay fg:red)[\]](bg:overlay fg:blue)'
behind = '[⇣\(${count}\)](bg:overlay fg:red)'

[time]
disabled = false
format = " [](fg:overlay)[ $time 󰧱 ]($style)[](fg:overlay)"
style = "bg:overlay fg:magenta"
time_format = "%I:%M%P"
use_12hr = true

[username]
disabled = false
format = "[](fg:overlay)[ $user]($style)[](fg:overlay) "
show_always = true
style_root = "bg:overlay fg:purple"
style_user = "bg:overlay fg:purple"

# === Languages ===

[c]
style = "bg:overlay fg:blue"
format = " [](fg:overlay)[ $symbol$version ]($style)[](fg:overlay)"
disabled = false
symbol = "󰙱 "
detect_extensions = ["c", "h"]
commands = [["gcc", "--version"], ["clang", "--version"], ["tcc", "--version"]]

[custom.cuda]
detect_extensions = ["cu", "cuh"]
symbol = ""
style = "bg:overlay fg:cyan"
format = " [](fg:overlay)[ $symbol $output ]($style)[](fg:overlay)"
command = "nvcc --version | awk '/release/ {print $6}'"
disabled = false

[custom.cpp]
detect_extensions = ["cpp", "hpp"]
symbol = "󰙲"
style = "bg:overlay fg:blue"
format = " [](fg:overlay)[ $symbol $output ]($style)[](fg:overlay)"
command = "g++ --version | awk 'NR==1 {print $3}'"
disabled = false

[elixir]
style = "bg:overlay fg:cyan"
format = " [](fg:overlay)[ $symbol$version ]($style)[](fg:overlay)"
disabled = false
symbol = " "

[elm]
style = "bg:overlay fg:cyan"
format = " [](fg:overlay)[ $symbol$version ]($style)[](fg:overlay)"
disabled = false
symbol = " "

[golang]
style = "bg:overlay fg:cyan"
format = " [](fg:overlay)[ $symbol$version ]($style)[](fg:overlay)"
disabled = false
symbol = " "

[haskell]
style = "bg:overlay fg:purple"
format = " [](fg:overlay)[ $symbol$version ]($style)[](fg:overlay)"
disabled = false
symbol = " "

[java]
style = "bg:overlay fg:orange"
format = " [](fg:overlay)[ $symbol$version ]($style)[](fg:overlay)"
disabled = false
symbol = " "

[julia]
style = "bg:overlay fg:magenta"
format = " [](fg:overlay)[ $symbol$version ]($style)[](fg:overlay)"
disabled = false
symbol = " "

[nodejs]
style = "bg:overlay fg:green"
format = " [](fg:overlay)[ $symbol$version ]($style)[](fg:overlay)"
disabled = false
symbol = "󰎙 "

[nim]
style = "bg:overlay fg:yellow"
format = " [](fg:overlay)[ $symbol$version ]($style)[](fg:overlay)"
disabled = false
symbol = "󰆥 "

[rust]
style = "bg:overlay fg:orange"
format = " [](fg:overlay)[ $symbol$version ]($style)[](fg:overlay)"
disabled = false
symbol = " "

[scala]
style = "bg:overlay fg:red"
format = " [](fg:overlay)[ $symbol$version ]($style)[](fg:overlay)"
disabled = false
symbol = " "

[python]
style = "bg:overlay fg:yellow"
format = " [](fg:overlay)[ $symbol$version ]($style)[](fg:overlay)"
disabled = false
symbol = ' '

[conda]
style = "bg:overlay fg:green"
format = " [](fg:overlay)[ $symbol$environment ]($style)[](fg:overlay)"
disabled = false
symbol = '🅒 '
