format = """
[ ](#a3aed2)\
$os\
$username\
[](bg:#769ff0 fg:#a3aed2)\
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
[](fg:#394260 bg:#212736)\
$lua\
$python\
$custom\
$c\
$nodejs\
$rust\
$golang\
$php\
[](fg:#212736 bg:#1d2230)\
$time\
[ ](fg:#1d2230)\
\n$character"""

[os]
disabled = false
style = "bg:#a3aed2 fg:#090c0c"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[username]
show_always = true
style_user = "bg:#a3aed2 fg:#090c0c"
style_root = "bg:#a3aed2 fg:#090c0c"

format = '[ $user ]($style)'


[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
disabled = false
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "bg:#394260"
stashed = '\$${count}'
ahead = "󰄿${count}"
behind = "󰄼${count}"
diverged = "⇕${count}"
conflicted = "=${count}"
deleted = "${count}"
renamed = "»${count}"
modified = "!${count}"
staged = "+${count}"
untracked = "?${count}"
[nodejs]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[python]
style = 'teal'
symbol = ' '
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
pyenv_version_name = true
pyenv_prefix = ''

[lua]
symbol = ' '

[c]
symbol = " "
format = "[$symbol($version)]($style)"
style = "bold blue"
detect_extensions = ["c", "h"]
commands = [["gcc", "--version"], ["clang", "--version"], ["tcc", "--version"]]

# [custom.cpp]
# symbol = " "
# format = "[$symbol($version)]($style)"
# style = "bold blue"
# detect_extensions = ["cc", "hpp", "cpp"]
# command = [["gcc", "--version"]]

[custom.cuda]
symbol = " "
format = "[$symbol($version)]($style)"
style = "bold blue"
detect_extensions = ["cu", "cuh"]
command = "nvcc --version"

[custom.cpp]
detect_extensions = ['cpp', 'hpp']
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($output) ]($style)'
command = "g++ --version | awk 'NR==1 {print $3}'"


[rust]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[golang]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[php]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'


# format = """
# $directory\
# $git_branch\
# $git_commit\
# $git_state\
# $git_metric\
# $git_status\
# $fill\
# $filetypes\
# $c\
# $custom\
# $python\
# $lua\
# $nodejs\
# $golang\
# $haskell\
# $rust\
# $ruby\
# $package\
# $aws\
# $docker_context\
# $jobs\
# $cmd_duration\
# $line_break\
# $character"""
#
# add_newline = true
# palette = 'nord'
#
# [directory]
# style = 'bold fg:dark_blue'
# format = '[$path ]($style)'
# truncation_length = 3
# truncation_symbol = '…/'
# truncate_to_repo = false
#
# [directory.substitutions]
# 'Documents' = '󰈙'
# 'Downloads' = ' '
# 'Music' = ' '
# 'Pictures' = ' '
#
# [git_branch]
# style = 'fg:green'
# symbol = ' '
# format = '[on](white) [$symbol$branch ]($style)'
#
# # [git_status]
# # style = 'fg:green'
# # format = '([$all_status$ahead_behind]($style) )'
# [git_status]
# style = 'fg:green'
# format = '([󰞉$conflicted 󰄴$staged 󰜥$modified 󰑕$renamed 󰛲$deleted 󰈈$untracked 󰏗$stashed$ahead_behind]($style) )'
#
# conflicted = '[$count](bold red)'
# staged = '[$count](bold green)'
# modified = '[$count](bold yellow)'
# renamed = '[$count](bold purple)'
# deleted = '[$count](bold red)'
# untracked = '[$count](bold blue)'
# stashed = '[$count](bold cyan)'
#
# ahead = '⇡[$count](bold green)'
# behind = '⇣[$count](bold red)'
# diverged = '⇕[$ahead_count](bold green)⇣[$behind_count](bold red)'
#
#
# [fill]
# symbol = ' '
#
# [character]
# success_symbol = '[❯](bold green)'
# error_symbol = '[❯](bold red)'
# vimcmd_symbol = '[❮](bold purple)'
# vimcmd_replace_one_symbol = '[ ](bold yellow)'
# vimcmd_replace_symbol = '[ ](bold yellow)'
# vimcmd_visual_symbol = '[󰒅 ](bold red)'
#
# [python]
# style = 'teal'
# symbol = ' '
# format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
# pyenv_version_name = true
# pyenv_prefix = ''
#
# [lua]
# symbol = ' '
#
# [c]
# symbol = " "
# format = "[$symbol($version)]($style)"
# style = "bold blue"
# detect_extensions = ["c", "h"]
# commands = [["gcc", "--version"], ["clang", "--version"], ["tcc", "--version"]]
#
# # [custom.cpp]
# # symbol = " "
# # format = "[$symbol($version)]($style)"
# # style = "bold blue"
# # detect_extensions = ["cc", "hpp", "cpp"]
# # command = [["gcc", "--version"]]
#
# [custom.cuda]
# symbol = " "
# format = "[$symbol($version)]($style)"
# style = "bold blue"
# detect_extensions = ["cu", "cuh"]
# command = "nvcc --version"
#
# [custom.cpp]
# detect_extensions = ['cpp', 'hpp']
# symbol = " "
# style = "bg:#86BBD8"
# format = '[ $symbol ($output) ]($style)'
# command = "g++ --version | awk 'NR==1 {print $3}'"
#
#
# [nodejs]
# style = 'blue'
# symbol = ' '
#
# [golang]
# style = 'blue'
# symbol = ' '
#
# [haskell]
# style = 'blue'
# symbol = ' '
#
# [rust]
# style = 'orange'
# symbol = ' '
#
# [ruby]
# style = 'blue'
# symbol = ' '
#
# [package]
# symbol = '󰏗 '
#
# [aws]
# symbol = ' '
# style = 'yellow'
# format = '[$symbol($profile )(\[$duration\] )]($style)'
#
# [docker_context]
# symbol = ' '
# style = 'fg:#06969A'
# format = '[$symbol]($style) $path'
# detect_files = ['docker-compose.yml', 'docker-compose.yaml', 'Dockerfile']
# detect_extensions = ['Dockerfile']
#
# [jobs]
# symbol = ' '
# style = 'red'
# number_threshold = 1
# format = '[$symbol]($style)'
#
# [cmd_duration]
# min_time = 500
# style = 'fg:gray'
# format = '[$duration]($style)'
#
# [palettes.nord]
# dark_blue = '#5E81AC'
# blue = '#81A1C1'
# teal = '#88C0D0'
# red = '#BF616A'
# orange = '#D08770'
# green = '#A3BE8C'
# yellow = '#EBCB8B'
# purple = '#B48EAD'
# gray = '#434C5E'
# black = '#2E3440'
# white = '#D8DEE9'
#
# [palettes.onedark]
# dark_blue = '#61afef'
# blue = '#56b6c2'
# red = '#e06c75'
# green = '#98c379'
# purple = '#c678dd'
# cyan = '#56b6c2'
# orange = '#be5046'
# yellow = '#e5c07b'
# gray = '#828997'
# white = '#abb2bf'
# black = '#2c323c'
#
